name: run-typhoon-model

on:
  workflow_dispatch

jobs:
  run-typhoon-model:
    runs-on: ubuntu-latest
    env:
      running-directory: ./IBF-Typhoon-model
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          python3-eccodes \
          libproj-dev \
          libgeos-dev \
          libspatialindex-dev \
          libudunits2-dev \
          libssl-dev \
          libgdal-dev \
        rm -rf /var/lib/apt/lists/*
    - name: Install Python dependencies
      run: |
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r requirements.txt
    - name: Install script
      run: |
        python -m pip install .
      working-directory: ${{ env.running-directory }}
    - name: Run script
      env:
        EMAIL_TO_LIST: ${{ secrets.EMAIL_TO_LIST }}
        EMAIL_CC_LIST: ${{ secrets.EMAIL_CC_LIST }}
        UCL_USERNAME: ${{ secrets.UCL_USERNAME }}
        UCL_PASSWORD: ${{ secrets.UCL_PASSWORD }}
        EMAIL_LOGIN: ${{ secrets.EMAIL_LOGIN }}
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
      run: |
        run-typhoon-model
      working-directory: ${{ env.running-directory }}
    - name: Send mail
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: ${{secrets.SMTP_SERVER}}
        server_port: ${{secrets.SMTP_PORT}}
        username: ${{secrets.EMAIL_LOGIN}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: "FAILED: ${{github.repository}} run job"
        body: GitHub Actions run job for ${{github.repository}} failed!
        to: ${{secrets.EMAIL_TO_LIST}}
        from: ${{secrets.EMAIL_FROM}}
        content_type: text/html
